name: FoxBukkitChat
main: net.doridian.foxbukkit.chat.FoxBukkitChat
version: 1.3.0
softdepend: [FoxBukkitPermissions]
commands:
  me:
    description: /me
    permission: foxbukkit.me
    usage: /<command> <action...>
    aliases:
      - action
  ignore:
    description: Ignore system management
    permission: foxbukkit.ignore
    usage: /<command> [add/remove/list/clear] <target>
  pm:
    description: Private message
    permission: foxbukkit.pm
    usage: /<command> <target> <msg...>
    aliases:
      - whisper
      - tell
      - msg
  reloadchat:
    description: Reload chat
    permission: foxbukkit.reloadchat
    usage: /<command>
