name: FoxBukkitChat
main: com.foxelbox.foxbukkit.chat.FoxBukkitChat
version: 1.3.0
commands:
  reloadclcommands:
    description: Reloads the ChatLink command list
    permission: foxbukkit.chatlink.reloadcommands
    usage: /<command>
