name: YiffBukkitChatComponent
main: de.doridian.yiffbukkit.chatcomponent.YBChatComponent
version: 1.0.0
commands:
    me:
        description: Well, /me
        usage: /<command> ACTION HERE
        aliases: emote
    pm:
        description: Like /tell
        usage: /<command> [target] MESSAGE HERE
        aliases: [tell, msg]
    conv:
        description: Opens conversation with target
        usage: /<command> [target]
    list:
        description: Lists all online players
        usage: /<command>
        aliases: who